deployment:
  tasks:
    - /bin/mkdir -p /home/qaseduc/public_html/jorquera/colegiosanpablo
    - /bin/rsync -av --delete --exclude='.git' --exclude='.cpanel.yml' ./ /home/qaseduc/public_html/jorquera/colegiosanpablo/