-- Respaldo lógico exacto previo basado en logica/qaseduc_colegio_spablo.sql.
-- Restaura los cuatro registros de página y los dos elementos multimedia del volcado.
SET NAMES utf8mb4;
START TRANSACTION;

INSERT INTO `sub_menu_paginas` (`id_pagina`, `id_sub_menu`, `titulo`, `bajada`, `contenido`, `imagen_hero`, `hero_video_url`, `hero_video_archivo`, `imagen_secundaria`, `video_url`, `video_archivo`, `boton_texto`, `boton_url`, `meta_title`, `meta_description`, `actualizado_en`, `actualizado_por`) VALUES
(1, 4, '', '', '', 'uploads/submenus/4/mermaid-diagram-20260606225019-e2388a.png', NULL, NULL, NULL, 'https://www.youtube.com/watch?v=u3A-Yqj8YIs', NULL, '', '', '', '', '2026-06-06 22:50:19', 1),
(2, 1, 'presentación', 'Bajada', '<p><strong>Poemas de un novelista constituy&oacute; la</strong> &uacute;nica incursi&oacute;n de Jos&eacute; Donoso en el g&eacute;nero po&eacute;tico. Esta obra reuni&oacute; una treintena de poemas, escritos a lo largo de una d&eacute;cad<strong>a</strong>, entre 1970 y 1980, en diversas residencias y lugares geogr&aacute;ficos (Calaicete, Sitges, Madrid). Jos&eacute; Donoso los tuvo guardados hasta que se atrevi&oacute; a publicarlos: &quot;Poco a poco, grano a grano, y por cierto que imperceptiblemente, fue form&aacute;ndose este libro de poemas. Jam&aacute;s tuve intenci&oacute;n de hacerlo. Pero sin darme cuenta, a distancia de a&ntilde;os unos de otros, aparecieron como una necesidad peque&ntilde;a pero diferente y complementario a la de mis novelas&quot; (Pr&oacute;logo. Poemas de un novelista. Santiago: Ganymedes, c1981. p. 11) El libro est&aacute; conformado por cuatro cap&iacute;tulos, seg&uacute;n el lugar donde los poemas fueron escritos: &quot;Diario de invierno en Calaceite (1971-72)&quot;; &quot;Tres Poemas de 1952&quot;; &quot;Madrid, 1979&quot;; &quot;Retratos (Sitges, 1977)&quot;. Jaime Quezada comenta que estos poemas &quot;se relacionan, a menudo, con la cr&oacute;nica, la confesi&oacute;n personal (&quot;soy lo que no hice, lo que no hago, lo que no har&eacute;), la s&iacute;ntesis de un pasado rom&aacute;ntico y memorial&quot; (&quot;Donoso en verso y prosa. La aventura po&eacute;tica&quot;, Ercilla, (2401): 43-44, 5 de agosto, 1981). Jos&eacute; Donoso siempre se sinti&oacute; c&oacute;modo como narrador. La poes&iacute;a fue para &eacute;l una forma de documentar un momento determinado de su vida: &quot;Pero no quiero ser poeta. La poes&iacute;a me parece un quehacer tan aterradoramente serio, solitario, definitivo, esencial, y las esencias, as&iacute;, escuetas e implacables, no son mi vocaci&oacute;n. S&eacute; muy bien que a ciertos niveles la forma de una novela y su elasticidad dependen de las infinitas v&eacute;rtebras de cada una de sus frases y palabras, formando una estructura real subyacente a la que aparece, lo que al fin y al cabo no es demasiado diferente al rigor de un poema. Pero la novela me da algo como m&aacute;s espacio donde moverme, el regocijo de la acumulaci&oacute;n de detalles y an&eacute;cdota que se construye a s&iacute; misma y es v&aacute;lida pese a que no se la someta a un escrutinio demasiado cruel, el c&oacute;digo interior que se genera secreto y amplio a la vez a trav&eacute;s de trivialidades, algo como la sobrepoblaci&oacute;n de una novela por decirlo de alg&uacute;n modo, y la aparente inutilidad de los distintos materiales que pueden llegar a constituirla: tiene para m&iacute; la prosa, y en especial la novela, algo de gregario y descuidado, que me gusta y donde me siento bien&quot; (Pr&oacute;logo, 15-16)</p>', NULL, '', NULL, NULL, '', NULL, 'Texto del botón', 'wwww.google.cl', 'qweqe', 'qeqe', '2026-06-15 09:47:11', 1),
(3, 14, '', '', 'wwwww', NULL, '', NULL, NULL, '', NULL, '', '', '', '', '2026-06-08 12:24:21', 1),
(4, 10, '', '', 'rwwerwe', NULL, '', NULL, NULL, '', NULL, '', '', '', '', '2026-06-13 13:08:52', 1);

INSERT INTO `sub_menu_pagina_media` (`id_media`, `id_sub_menu`, `tipo`, `archivo`, `url`, `titulo`, `descripcion`, `visible`, `orden`, `creado_en`) VALUES
(1, 4, 'imagen', 'uploads/submenus/4/portada-1-20260606225019-a67215.jpg', NULL, 'prueba', NULL, 1, 1, '2026-06-07 02:50:19'),
(13, 4, 'imagen', 'uploads/submenus/4/portada-2-20260606225019-0da28c.jpg', NULL, 'Imagen de galería', NULL, 1, 2, '2026-06-15 02:01:49');

COMMIT;
